import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const GRID_GAP = 12;
const CARD_W = (SCREEN_W - 16 * 2 - GRID_GAP) / 2;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FAFAFA' },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  backBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backBtnText: { fontSize: 20, color: '#333' },
  headerTitle: { fontSize: 17, fontWeight: '700', color: '#1A1A1A' },

  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    gap: 8,
  },
  searchIcon: { fontSize: 14 },
  searchInput: { flex: 1, fontSize: 14, color: '#333', padding: 0 },

  deptScroll: { marginTop: 16, flexGrow: 0 },
  deptScrollContent: { paddingHorizontal: 16, gap: 16 },
  deptItem: { alignItems: 'center', width: 56 },
  deptIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  deptIcon: { fontSize: 22 },
  deptLabel: { fontSize: 11, color: '#555', textAlign: 'center' },

  listScroll: { flex: 1, marginTop: 16 },
  listContent: { paddingHorizontal: 16, paddingBottom: 24 },

  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: GRID_GAP,
  },
  hospitalCard: {
    width: CARD_W,
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardImage: {
    width: '100%',
    height: CARD_W * 0.75,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImageText: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
  },
  statusBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusText: { fontSize: 10, fontWeight: '700', color: '#333' },

  cardInfo: { padding: 10 },
  hospitalName: { fontSize: 13, fontWeight: '700', color: '#1A1A1A', marginBottom: 3 },
  hospitalDept: { fontSize: 12, color: '#4CAF82', fontWeight: '600', marginBottom: 6 },
  cardBottomRow: { flexDirection: 'row', justifyContent: 'space-between' },
  hospitalDistance: { fontSize: 11, color: '#888' },
  hospitalRating: { fontSize: 11, color: '#888' },

  moreBtn: {
    alignSelf: 'center',
    marginTop: 16,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  moreBtnText: { fontSize: 13, color: '#555', fontWeight: '600' },

  footer: {
    marginTop: 32,
    paddingTop: 20,
    paddingHorizontal: 8,
    borderTopWidth: 1,
    borderTopColor: '#EAEAEA',
    alignItems: 'center',
  },
  footerTitle: { fontSize: 13, fontWeight: '700', color: '#666', marginBottom: 6 },
  footerText: {
    fontSize: 11,
    color: '#AAAAAA',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 8,
  },
  footerCopyright: { fontSize: 10, color: '#CCCCCC' },

  // ── 상세 모달 스타일 ──
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    height: '85%',
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  modalHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A1A',
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
  },
  modalCloseBtnText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '700',
  },
  modalScroll: {
    flex: 1,
  },
  modalScrollContent: {
    paddingHorizontal: 24,
    paddingVertical: 20,
    gap: 20,
  },
  modalImageArea: {
    width: '100%',
    height: 160,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  modalImageText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  modalImageSub: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '600',
  },
  modalSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
    paddingBottom: 16,
  },
  modalTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  modalHospitalName: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A1A1A',
  },
  modalStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modalStatusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  modalDeptText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4CAF82',
    marginBottom: 8,
  },
  modalMetaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  modalMetaText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  modalAddressText: {
    fontSize: 13,
    color: '#555',
    lineHeight: 18,
    fontWeight: '500',
  },
  modalSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 8,
  },
  modalBodyText: {
    fontSize: 13,
    color: '#444',
    lineHeight: 20,
    fontWeight: '500',
  },
  modalDoctorName: {
    fontSize: 14,
    fontWeight: '800',
    color: '#333',
    marginBottom: 4,
  },
  modalBioText: {
    fontSize: 13,
    color: '#555',
    lineHeight: 19,
    fontWeight: '500',
  },
  modalActionRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 10,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F5F5F5',
  },
  modalReserveBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#4CAF82',
    borderRadius: 28,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalReserveBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4CAF82',
  },
  modalTelemedicineBtn: {
    flex: 1,
    backgroundColor: '#4CAF82',
    borderRadius: 28,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTelemedicineBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  modalPhoneText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '600',
    marginTop: 4,
  },
  doctorItemCard: {
    backgroundColor: '#F9F9F9',
    borderRadius: 20,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  doctorBioList: {
    marginTop: 4,
    gap: 2,
  },
  bookingSection: {
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
    paddingBottom: 16,
    marginBottom: 16,
  },
  bookingSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 12,
  },
  doctorSelectRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  doctorSelectBtn: {
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  doctorSelectBtnActive: {
    backgroundColor: '#E8F5E9',
    borderColor: '#4CAF82',
  },
  doctorSelectBtnText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
  },
  doctorSelectBtnTextActive: {
    color: '#2E7D32',
    fontWeight: '800',
  },
  calendarScroll: {
    gap: 10,
    paddingVertical: 4,
  },
  dateCard: {
    width: 68,
    height: 76,
    backgroundColor: '#F5F5F5',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    gap: 4,
  },
  dateCardActive: {
    backgroundColor: '#E8F5E9',
    borderColor: '#4CAF82',
  },
  dateCardWeekend: {
    backgroundColor: '#FFEBEE',
    borderColor: '#FFCDD2',
  },
  dateLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#666',
  },
  dateLabelActive: {
    color: '#2E7D32',
    fontWeight: '800',
  },
  dayLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#444',
  },
  timeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timeSlot: {
    width: '23%',
    backgroundColor: '#F5F5F5',
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  timeSlotActive: {
    backgroundColor: '#E8F5E9',
    borderColor: '#4CAF82',
  },
  timeText: {
    fontSize: 12,
    color: '#555',
    fontWeight: '600',
  },
  timeTextActive: {
    color: '#2E7D32',
    fontWeight: '800',
  },
  bookingActionRow: {
    paddingHorizontal: 20,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F5F5F5',
  },
  bookingConfirmBtn: {
    backgroundColor: '#4CAF82',
    borderRadius: 28,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingConfirmBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
  },
});
